name: Release

on:
  push:
    branches: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write      # to create release
      issues: write        # to comment on released issues
      pull-requests: write # to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || true
        
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.3
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          HUSKY: 0    # Disable Husky hooks during semantic-release
